<?xml version="1.0"?>
<robot name="r2d2" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="polelen" value="0.2" />
  <xacro:property name="bodylen" value="0.6" />
  <xacro:property name="baselen" value="0.4" />
  <xacro:property name="wheeldiam" value="0.07" />

  <xacro:include filename="$(find r2d2_control)/urdf/utils_ros2_control_with_diffbotsytem.urdf.xacro"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />

  <xacro:ros2_control_system suffix="front" />
  <xacro:ros2_control_system suffix="back" />

  <ros2_control name="front_wheel_system" type="system">
    <!-- Need clone and build https://github.com/ros-controls/ros2_control_demos -->
    <hardware>
      <plugin>ros2_control_demo_hardware/DiffBotSystemHardware</plugin>
      <param name="example_param_hw_start_duration_sec">2.0</param>
      <param name="example_param_hw_stop_duration_sec">3.0</param>
    </hardware>

    <!-- for diff_drive_controller -->
    <!-- https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller.cpp#L122-L144 -->
    <!-- Need velocity command interface and position state interface-->
    <joint name="left_front_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-1</param>
        <param name="max"> 1</param>
      </command_interface>
      <!-- DiffBotSystemHardware need two states -->
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_front_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-1</param>
        <param name="max"> 1</param>
      </command_interface>
      <!-- DiffBotSystemHardware need two states -->
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>



  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="head_swivel" type="fixed">
    <parent link="base_link"/>
    <child link="head"/>
    <origin xyz="0 0 ${bodylen/2}"/>
  </joint>
  <link name="box">
    <visual>
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="-0.04 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="tobox" type="fixed">
    <parent link="head"/>
    <child link="box"/>
    <origin xyz="${.707*width+0.04} 0 ${.707*width}"/>
  </joint>

  <!-- Gazebo plugin for ROS2 Control -->
  <gazebo>
    <!-- <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters> $(find gazebo_r2d2)/config/diff_drive_controller.yaml </parameters>
    </plugin> -->
  </gazebo>

</robot>