<?xml version="1.0"?>
<robot name="r2d2" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="polelen" value="0.2" />
  <xacro:property name="bodylen" value="0.6" />
  <xacro:property name="baselen" value="0.4" />
  <xacro:property name="wheeldiam" value="0.07" />

  <xacro:include filename="$(find r2d2_control)/urdf/utils.urdf.xacro"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />
 
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="head_swivel" type="fixed">
    <parent link="base_link"/>
    <child link="head"/>
    <origin xyz="0 0 ${bodylen/2}"/>
  </joint>
  <link name="box">
    <visual>
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="-0.04 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="tobox" type="fixed">
    <parent link="head"/>
    <child link="box"/>
    <origin xyz="${.707*width+0.04} 0 ${.707*width}"/>
  </joint>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>

    <plugin name='front_diff_drive' filename='libgazebo_ros_diff_drive.so'>

      <update_rate>50</update_rate>
      <left_joint>left_front_wheel_joint</left_joint>
      <right_joint>right_front_wheel_joint</right_joint>
      <wheel_separation>${width}</wheel_separation>
      <wheel_diameter>${wheeldiam/2}</wheel_diameter>
      <robot_base_frame>base_link</robot_base_frame>
			<publishWheelJointState>true</publishWheelJointState>

    </plugin>

    <plugin name='back_diff_drive' filename='libgazebo_ros_diff_drive.so'>

      <update_rate>50</update_rate>
      <left_joint>left_back_wheel_joint</left_joint>
      <right_joint>right_back_wheel_joint</right_joint>

      <wheel_separation>${width}</wheel_separation>
      <wheel_diameter>${wheeldiam}</wheel_diameter>
      <robot_base_frame>base_link</robot_base_frame>
			<publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

</robot>